services:
  ollama:
    # image: ollama/ollama:latest
    build: Dockerfile-ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/data
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # build: .
    build: Dockerfile
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434


volumes:
  ollama_data:
    # driver: local